config/routes.rb
Rails.application.routes.draw do
  resources :games_users, only: [:create, :destroy]
  resources :user_proficiencies, only: [:create, :destroy]
  resources :teams
  resources :users, except: :new do
    member do
      get :confirm_account
    end
  end
  resources :user_teams
  resources :proficiency_posts, only: :create
  resources :games, only: [:create, :show, :destroy] do
    resources :proficiencies, except: :index do
      resources :proficiency_posts, only: [:create, :destroy]
    end
  end

  # Root of site
  root 'sessions#new'

  get    'profile' => 'users#show'
  get    'confirm' => 'pages#confirm'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post 'teams/:id/requestDecision' => 'teams#requestDecision', as: :request_decision
  post 'users/:id/endorse/:proficiency_id' => 'users#endorse', as: :endorse
  post   'users/:id/confirm_account' => 'users#send_confirmation_email', as: :confirm_account

  get    'admin'   => 'pages#admin'
  post   'admin'   => 'pages#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  namespace :search do
    resources :all
    resources :proficiencies
    resources :games
  end
end

app/models/user_proficiency.rb
class UserProficiency < ActiveRecord::Base
  validates :user_id, uniqueness: { scope: :proficiency_id,
    message: "Proficiency already added to users profile"}
  belongs_to :user
  belongs_to :proficiency
end

app/controllers/user_proficiencies_controller.rb
class UserProficienciesController < ApplicationController
  before_action :set_user_proficiency, only: [:show, :edit, :update, :destroy]

  # GET /user_proficiencies
  # GET /user_proficiencies.json
  def index
    @user_proficiencies = UserProficiency.all
  end

  # GET /user_proficiencies/1
  # GET /user_proficiencies/1.json
  def show
  end

  # GET /user_proficiencies/new
  def new
    @user_proficiency = UserProficiency.new
  end

  # GET /user_proficiencies/1/edit
  def edit
  end

  # POST /user_proficiencies
  # POST /user_proficiencies.json
  def create
    @user_proficiency = UserProficiency.new(user_proficiency_params)
    @proficiency = Proficiency.find(@user_proficiency.proficiency_id)
    respond_to do |format|
      if @user_proficiency.save
        format.js {}
      else
        format.json { render json: @user_proficiency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_proficiencies/1
  # PATCH/PUT /user_proficiencies/1.json
  def update
    respond_to do |format|
      if @user_proficiency.update(user_proficiency_params)
        format.html { redirect_to @user_proficiency, notice: 'User proficiency was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_proficiency }
      else
        format.html { render :edit }
        format.json { render json: @user_proficiency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_proficiencies/1
  # DELETE /user_proficiencies/1.json
  def destroy
    @user_proficiency.active = INACTIVE
    respond_to do |format|
      if @user_proficiency.save
        format.js {}
      else
        format.json { render json: @user_proficiency.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_proficiency
      @user_proficiency = UserProficiency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_proficiency_params
      params.require(:user_proficiency).permit(:endorsements, :user_id, :proficiency_id)
    end
end

app/helpers/user_proficiencies_helper.rb
module UserProficienciesHelper
end

app/views/user_proficiencies/_form.html.erb
<%= form_for(@user_proficiency) do |f| %>
  <% if @user_proficiency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_proficiency.errors.count, "error") %> prohibited this user_proficiency from being saved:</h2>

      <ul>
      <% @user_proficiency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :endorsements %><br>
    <%= f.text_area :endorsements %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_proficiencies/_user_proficiency.html.erb
<tr id="g_<%= @proficiency.game.id %>_p_<%= @proficiency.id %>">
  <td class="collapsing"><%= image_tag @proficiency.picture_url, class: 'ui tiny left floated image' %></td>
  <td><%= link_to @proficiency.name, '/games/' + @proficiency.game.name.downcase.tr(' ', '-') + '/proficiencies/' + @proficiency.name.downcase %></td>
  <td><%= @proficiency.description %></td>
  <td><%= button_to 'Endorse', endorse_path(current_user.username, @proficiency.id), method: :post, class: 'ui positive button' %></td>
</tr>

app/views/user_proficiencies/create.js.erb
$("<%= escape_javascript(render @user_proficiency) %>")
  .appendTo("#game_<%= @proficiency.game_id %>")
  .transition('fade right');

app/views/user_proficiencies/destroy.js.erb
$("#g_<%= @user_proficiency.proficiency.id %>")
  .transition('fade right');

app/views/user_proficiencies/edit.html.erb
<h1>Editing User Proficiency</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_proficiency %> |
<%= link_to 'Back', user_proficiencies_path %>

app/views/user_proficiencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Proficiencies</h1>

<table>
  <thead>
    <tr>
      <th>Endorsements</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_proficiencies.each do |user_proficiency| %>
      <tr>
        <td><%= user_proficiency.endorsements %></td>
        <td><%= link_to 'Show', user_proficiency %></td>
        <td><%= link_to 'Edit', edit_user_proficiency_path(user_proficiency) %></td>
        <td><%= link_to 'Destroy', user_proficiency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User proficiency', new_user_proficiency_path %>

app/views/user_proficiencies/new.html.erb
<h1>New User Proficiency</h1>

<%= render 'form' %>

<%= link_to 'Back', user_proficiencies_path %>

app/views/user_proficiencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endorsements:</strong>
  <%= @user_proficiency.endorsements %>
</p>

<%= link_to 'Edit', edit_user_proficiency_path(@user_proficiency) %> |
<%= link_to 'Back', user_proficiencies_path %>