config/routes.rb
Rails.application.routes.draw do
  resources :games_users, only: [:create, :destroy]
  resources :user_proficiencies, only: [:create, :destroy]
  resources :teams
  resources :users, except: :new do
    member do
      get :confirm_account
    end
  end
  resources :user_teams
  resources :proficiency_posts, only: :create
  resources :games, only: [:create, :show, :destroy] do
    resources :proficiencies, except: :index do
      resources :proficiency_posts, only: [:create, :destroy]
    end
  end

  # Root of site
  root 'sessions#new'

  get    'profile' => 'users#show'
  get    'confirm' => 'pages#confirm'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post 'teams/:id/requestDecision' => 'teams#requestDecision', as: :request_decision
  post 'users/:id/endorse/:proficiency_id' => 'users#endorse', as: :endorse
  post   'users/:id/confirm_account' => 'users#send_confirmation_email', as: :confirm_account

  get    'admin'   => 'pages#admin'
  post   'admin'   => 'pages#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  namespace :search do
    resources :all
    resources :proficiencies
    resources :games
  end
end

app/views/pages/_header.html.erb
<div class="following bar">
  <div class="ui container">
    <div class="ui secondary menu">
      <div class="item">
        <div class="ui tiny image">
          <%= link_to image_tag('logo.svg', alt: 'TeamUp'), root_url %>
        </div>
      </div>
      <div class="right menu">
        <% if logged_in? %>
          <% if account_confirmed? %>
          <div class="ui category search item">
            <div class="ui transparent black icon input">
              <input class="prompt" type="text" placeholder="Search...">
              <i class="search icon"></i>
            </div>
            <div class="results"></div>
            <a class="ui icon item" title="Advanced search">
              <i class="sitemap grey icon" title="Advanced search"></i>
            </a>
          </div>

          <div class="ui text menu">
            <div class="item">
              <%= link_to "Users", users_path %>
            </div>
            <div class="item">
              <%= link_to "Teams", teams_path %>
            </div>
          </div>

          <div class="ui dropdown item">
            <%= current_user.username %>
            <i class="dropdown icon"></i>
            <div class="menu">
              <%= link_to "Profile", current_user, class: 'item' %>
              <%= link_to "New Team", new_team_path, class: 'item' %>
              <%= link_to "Settings", edit_user_path(current_user), class: 'item' %>
              <% if is_admin? %>
                <%= link_to 'Admin Panel', admin_path, class: 'item' %>
              <% end %>

              <%= link_to "Log out", logout_path, method: "delete", class: 'item' %>
            </div>
          </div>
          <% else  %>
          <div class="ui dropdown item">
            <%= current_user.username %>
            <i class="dropdown icon"></i>
            <div class="menu">
              <%= link_to "Log out", logout_path, method: "delete", class: 'item' %>
            </div>
          </div>
          <% end %>

        <% else %>
          <div class="item">
              <%= link_to "Log in", login_path %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/admin.html.erb
<div class="admin-page">
  <h1 class="ui center aligned header padding-top">Admin Panel for <%= @current_user.username %></h1>
  <div class="ui container">

    <p id="notice"><%= notice %></p>

    <% if @permission >= 5 %>
      <div class="ui section divider"></div>
      <div class="ui text container">
        <div class="ui form">
          <div class="ui segment">
            <h3 class="ui centered aligned header padding-top">Edit User Permissions</h3>
            <div class="field">
              <label for="[id]">User</label>
              <%= collection_select( @user, :id, User.all, :id, :username, {}, {:class => 'ui fluid selection dropdown'}) %>
            </div>

            <div class="actions right-align">
              <button type="submit" name="edit_user" class="ui disabled submit button">Edit User</button>
            </div>
          </div>
        </div>
      </div>

    <% end %>

    <% if @permission >= 4 %>
      <div class="ui section divider"></div>
      <div class="ui text container">
        <%= form_for @game, :url => url_for(:controller => 'pages', :action => 'create'), :html => {:class => 'ui form'} do |f| %>
          <div class="ui segment">

            <h3 class="ui centered aligned header padding-top">Add Game</h3>

            <% if @game.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

                <ul>
                <% @game.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>

              </div>
            <% end %>

            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description %>
            </div>

            <div class="field">
              <%= f.label :picture_url %>
              <%= f.text_area :picture_url %>
            </div>

            <div class="actions right-align">
              <%= f.submit 'Create Game', class: 'ui blue submit button', name: 'create_game' %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if @permission >= 3 %>
      <div class="ui section divider"></div>
      <div class="ui text container">

        <%= form_for @proficiency, :url => url_for(:controller => 'pages', :action => 'create'), :html => {:class => 'ui form'} do |f| %>
          <div class="ui segment">

            <h3 class="ui centered aligned header padding-top">Add Proficiency</h3>

            <% if @proficiency.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@proficiency.errors.count, "error") %> prohibited this proficiency from being saved:</h2>

                <ul>
                <% @proficiency.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>

              </div>
            <% end %>

            <div class="field">
              <%= f.label :game %>
              <%= f.collection_select( :game_id, Game.all, :id, :name, {}, {:class => 'ui fluid selection dropdown'}) %>
            </div>
            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description %>
            </div>
            <div class="field">
              <%= f.label :picture_url %>
              <%= f.text_area :picture_url %>
            </div>
            <div class="actions right-align">
              <%= f.submit 'Create Proficiency', class: 'ui blue submit button', name: 'create_proficiency' %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/confirm.html.erb
<div class="ui container aligned-text">
In order to take advantage of the wonderful workings of TeamUp, it's important that we know that you're as committed to this process as we are. By confirming your email, you agree to sign away all doubts and worries to us, and let our super-duper algorithms do all the worrying for you.
  <br/>
  <br/>
  <div class="centered">
    <%= button_to [:confirm_account, @current_user], class: "ui positive button", data: { disable_with: "Email Sent!" } do %>
      TeamUp Now, <%= @current_user.username %>!
    <% end %>
  </div>
</div>