config/routes.rb
Rails.application.routes.draw do
  resources :games_users, only: [:create, :destroy]
  resources :user_proficiencies, only: [:create, :destroy]
  resources :teams
  resources :users, except: :new do
    member do
      get :confirm_account
    end
  end
  resources :user_teams
  resources :proficiency_posts, only: :create
  resources :games, only: [:create, :show, :destroy] do
    resources :proficiencies, except: :index do
      resources :proficiency_posts, only: [:create, :destroy]
    end
  end

  # Root of site
  root 'sessions#new'

  get    'profile' => 'users#show'
  get    'confirm' => 'pages#confirm'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post 'teams/:id/requestDecision' => 'teams#requestDecision', as: :request_decision
  post 'users/:id/endorse/:proficiency_id' => 'users#endorse', as: :endorse
  post   'users/:id/confirm_account' => 'users#send_confirmation_email', as: :confirm_account

  get    'admin'   => 'pages#admin'
  post   'admin'   => 'pages#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  namespace :search do
    resources :all
    resources :proficiencies
    resources :games
  end
end

app/models/proficiency.rb
class Proficiency < ActiveRecord::Base
  has_many :proficiency_posts
  has_many :user_proficiencies
  belongs_to :game
  has_many :users, through: :user_proficiencies
  accepts_nested_attributes_for :proficiency_posts

  validates_presence_of :slug

  def to_param
    slug
  end
end

app/controllers/proficiencies_controller.rb
class ProficienciesController < ApplicationController
  before_action :set_proficiency, :set_game, only: [:show, :edit, :update, :destroy]
  helper_method :get_profile_picture, :endorsements_for_proficiency

  # GET /proficiencies
  # GET /proficiencies.json
  def index
    @proficiencies = Proficiency.all
  end

  # GET /proficiencies/1
  # GET /proficiencies/1.json
  def show
    @proficiency_posts = ProficiencyPost.where(proficiency_id: @proficiency.id)
    @proficiency_post ||= ProficiencyPost.new
  end

  # GET /proficiencies/new
  def new
    @proficiency = Proficiency.new
  end

  # GET /proficiencies/1/edit
  def edit
  end

  # POST /proficiencies
  # POST /proficiencies.json
  def create
    @proficiency = Proficiency.new(proficiency_params)
    @proficiency.slug = @proficiency.name.downcase.gsub(" ", "-")

    respond_to do |format|
      if @proficiency.save
        format.html { redirect_to @proficiency, notice: 'Proficiency was successfully created.' }
        format.json { render :show, status: :created, location: @proficiency }
      else
        format.html { render :new }
        format.json { render json: @proficiency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proficiencies/1
  # PATCH/PUT /proficiencies/1.json
  def update
    respond_to do |format|
      if @proficiency.update(proficiency_params)
        format.html { redirect_to @proficiency, notice: 'Proficiency was successfully updated.' }
        format.json { render :show, status: :ok, location: @proficiency }
      else
        format.html { render :edit }
        format.json { render json: @proficiency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proficiencies/1
  # DELETE /proficiencies/1.json
  def destroy
    @proficiency.destroy
    respond_to do |format|
      format.html { redirect_to proficiencies_url, notice: 'Proficiency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_profile_picture(username)
    if user = User.find_by_slug(username.downcase)
      return user.picture_url
    end
    "http://i.istockimg.com/file_thumbview_approve/64396363/3/stock-photo-64396363-businessman-silhouette-as-avatar-or-default-profile-picture.jpg"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proficiency
      if !(@proficiency = Proficiency.find_by_slug(params[:id]))
        raise ActionController::RoutingError.new('Not Found')
      end
    end

    def set_game
      @game = Game.find_by_slug(params[:game_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proficiency_params
      params.require(:proficiency).permit(:game_id, :name, :description, :picture_url)
    end
end

app/controllers/search/proficiencies_controller.rb
require 'fuzzy_match'

class Search::ProficienciesController < ApplicationController

  # GET /search/proficiencies?game={id}&q={query}
  def index
    game = Game.find(params[:game])

    if params[:q].blank?
      proficiencies = game.proficiencies
    else
      proficiencies = FuzzyMatch.new(game.proficiencies, :read => :name).find_all(params[:q])
    end

    results = []
    proficiencies.each do |proficiency|
      results.push({
        name: proficiency.name,
        value: proficiency.id
      })
    end

    render :json => {
      success: true,
      results: results
    }
  end
end

app/helpers/proficiencies_helper.rb
module ProficienciesHelper
end

app/views/proficiencies/_form.html.erb
<%= form_for(@proficiency) do |f| %>
  <% if @proficiency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proficiency.errors.count, "error") %> prohibited this proficiency from being saved:</h2>

      <ul>
      <% @proficiency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :game %><br>
    <%= f.collection_select( :game_id, Game.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br>
    <%= f.text_area :picture_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proficiencies/_proficiency.html.erb
<tr>
  <td class="collapsing"><%= image_tag proficiency.picture_url, class: 'ui tiny left floated image' %></td>
  <td><%= link_to proficiency.name, '/games/' + proficiency.game.name.downcase.tr(' ', '-') + '/proficiencies/' + proficiency.name.downcase %></td>
  <td><%= proficiency.description %></td>
  <td>
    <% endorsements_for_proficiency(proficiency.id).each do |endorser| %>
      <%= link_to(image_tag(endorser.picture_url, class: 'ui avatar image', data: {title: endorser.username}), user_path(endorser)) %>
    <% end %>
    <% if !endorsed?(proficiency.id) %>
      <%= button_to 'Endorse', endorse_path(@user.username, proficiency.id), method: :post, class: 'ui positive button' %>
    <% end %>
  </td>
  <td class="hidden collapsing deletable game_<%= proficiency.game.id %>">
    <button type="button" class="ui red button">Delete</button>
  </td>
</tr>

app/views/proficiencies/edit.html.erb
<h1>Editing Proficiency</h1>

<%= render 'form' %>

<%= link_to 'Show', @proficiency %> |
<%= link_to 'Back', proficiencies_path %>

app/views/proficiencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Proficiencies</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Name</th>
      <th>Description</th>
      <th>Picture url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proficiencies.each do |proficiency| %>
      <tr>
        <td><%= proficiency.game_id %></td>
        <td><%= proficiency.name %></td>
        <td><%= proficiency.description %></td>
        <td><%= proficiency.picture_url %></td>
        <td><%= link_to 'Show', proficiency %></td>
        <td><%= link_to 'Edit', edit_proficiency_path(proficiency) %></td>
        <td><%= link_to 'Destroy', proficiency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proficiency', new_proficiency_path %>

app/views/proficiencies/new.html.erb
<h1>New Proficiency</h1>

<%= render 'form' %>

<%= link_to 'Back', proficiencies_path %>

app/views/proficiencies/show.html.erb
<div class="proficiency-page">
  <div class="ui container proficiency-header">
    <h1 class="ui centered huge header"><%= @proficiency.name %></h1>
    <%= image_tag @proficiency.picture_url, class: "ui centered bordered small image", alt: "Proficiency Picture" %>
    <h1 class="ui centered huge header"><%= @game.name %></h1>

    <h3 class="ui header">Description</h3>
    <p><%= @proficiency.description %></p>
  </div>

  <% if @proficiency_posts.any? %>
  <div class="ui container">
    <div class="ui section divider"></div>

    <h2 class="ui header">Posts</h2>

    <div class="ui list">
      <% @proficiency_posts.reverse.each do |proficiency_post| %>
      <div class="ui segment">
        <h2 class="ui header">
          <%= image_tag get_profile_picture(proficiency_post.username), alt: "Profile Picture" %>
          <div class="content">
            <%= proficiency_post.title %>
            <div class="sub header">
              <%= link_to proficiency_post.username, '/users/' + proficiency_post.username.downcase  %>
              - <%= proficiency_post.date.to_formatted_s(:long) %></div>
          </div>
        </h2>
        <div class="ui content">
          <%= proficiency_post.content %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="ui section divider"></div>
  </div>
  <% end %>

  <% if @permission > 1 %>
  <div class="ui container">
    <%= form_for(@proficiency_post, :html => {:class => 'ui add proficiency post form', id: 'addProficiencyPostForm'}) do |f| %>

    <div class="ui segment">

      <h3 class="ui centered aligned header padding-top">Add a Post</h3>

      <% if @game.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

        <ul>
          <% @game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>

      </div>
      <% end %>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content %>
      </div>

      <%= f.hidden_field :proficiency_id, :value => @proficiency.id %>
      <%= f.hidden_field :username, :value => current_user.username %>

      <div class="actions right-align">
        <%= f.submit 'Submit Post', class: 'ui blue submit button' %>
      </div>

      <div class="ui error message"></div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>