config/routes.rb
Rails.application.routes.draw do
  resources :games_users, only: [:create, :destroy]
  resources :user_proficiencies, only: [:create, :destroy]
  resources :teams
  resources :users, except: :new do
    member do
      get :confirm_account
    end
  end
  resources :user_teams
  resources :proficiency_posts, only: :create
  resources :games, only: [:create, :show, :destroy] do
    resources :proficiencies, except: :index do
      resources :proficiency_posts, only: [:create, :destroy]
    end
  end

  # Root of site
  root 'sessions#new'

  get    'profile' => 'users#show'
  get    'confirm' => 'pages#confirm'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post 'teams/:id/requestDecision' => 'teams#requestDecision', as: :request_decision
  post 'users/:id/endorse/:proficiency_id' => 'users#endorse', as: :endorse
  post   'users/:id/confirm_account' => 'users#send_confirmation_email', as: :confirm_account

  get    'admin'   => 'pages#admin'
  post   'admin'   => 'pages#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  namespace :search do
    resources :all
    resources :proficiencies
    resources :games
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :teams
  has_many :proficiencies
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :proficiencies
  validates :name, presence: true, uniqueness: true
  validates_presence_of :slug

  def to_param
    slug
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, :set_proficiencies, only: [:show, :edit, :update, :destroy]
  helper_method :proficiency_link

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find_by_slug(params[:id])

    if @game.nil?
      raise ActionController::RoutingError.new('Not Found')
    end

    @proficiencies = Proficiency.where(game_id: @game.id)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.slug = @game.name.downcase.gsub(" ", "-")

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def proficiency_link(proficiency)
     '/games/' + @game.name.downcase.tr(' ', '-') + '/proficiencies/' + proficiency.downcase.tr(' ', '-')
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find_by_slug(params[:id])
    end

    def set_proficiencies
      @proficiencies = @game.proficiencies
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :picture_url)
    end
end

app/controllers/search/games_controller.rb
require 'fuzzy_match'

class Search::GamesController < ApplicationController

  # GET /search/games?q={query}
  def index

    if params[:q].blank?
      games = Game.all
    else
      games = FuzzyMatch.new(Game.all, :read => :name).find_all(params[:q])
    end

    results = []
    games.each do |game|
      results.push({
        name: game.name,
        value: game.id
      })
    end

    render :json => {
      success: true,
      results: results
    }
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br>
    <%= f.text_area :picture_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div class="ui section divider"></div>

<div class="ui container" id="g_<%= game.id %>">
  <div class="ui grid">
        <div class="left floated twelve wide column">
          <h2 class="ui header">
            <%= link_to game.name, '/games/' + game.name.downcase.tr(' ', '-')  %>
          </h2>
        </div>
        <div class="right floated">
            <button type="button"class="ui basic button edit_game" data="<%= game.id %>">Edit</button>
            <%= button_to 'Delete', destroy_user_game_path(game.id), method: :post, remote: true, class: "ui hidden red button deletable game_#{game.id}"  %>
            <div class="hidden deletable game_<%= game.id %>">
            </div>
        </div>
      </div>
  <div class="ui container">
    <div class="ui two column grid">
      <div class="three wide column middle aligned centered">
        <%= image_tag game.picture_url, class: 'ui small left floated image' %>
      </div>
      <div class="thirteen wide column">
        <strong>Teams:</strong>
        <div class="ui list">
          <% get_teams_for_game(game.id).each do |team| %>
          <div class="item"><%= link_to team.name, '/teams/' + team.name.downcase.tr(' ', '-')  %></div>
          <% end %>
        </div>
        <strong>Game Description:</strong>
        <p><%= game.description %></p>
      </div>
    </div>
  </div>

  <h3 class="ui header">Proficiencies</h3>
  <table class="ui celled table attached">
    <thead>
      <tr>
        <th> </th>
        <th>Name</th>
        <th>Description</th>
        <th>Endorsements</th>
        <th class="hidden deletable game_<%= game.id %>"> </th>
      </tr>
    </thead>

    <tbody id="game_<%= game.id %>">
      <%= render proficiencies_for_game(game) %>
    </tbody>
  </table>
  <% if is_current_user? %>
  <div class="ui bottom attached blue button add_proficiency_to_user" data="<%= game.id %>">Add Proficiency</div>
  <% end %>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= game.picture_url %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="game-page">
  <div class="ui container game-header">
    <%= image_tag @game.picture_url, class: "ui centered bordered large circular image", alt: "Game Picture" %>
    <h1 class="ui centered huge header"><%= @game.name %></h1>

    <h3 class="ui header">Description</h3>
    <p><%= @game.description %></p>

    <h3 class="ui header">Proficiencies</h3>
    <table class="ui celled striped table">
      <thead>
        <tr>
          <th> </th>
          <th>Name</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% @proficiencies.each do |proficiency| %>
            <tr>
              <td class="collapsing"><%= image_tag proficiency.picture_url, class: 'ui small left floated image' %></td>
              <td>
                <%= link_to proficiency.name, proficiency_link(proficiency.name)  %>
              <td><%= proficiency.description %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>